### ISSUE TITLE
How to fix this error? - name of parameter doesnt start with $

### ISSUE THREAD

**Issue by philippfrenzel** [Speicher210/Reflection#1]
Following error message:

[Wingu\OctopusCore\Reflection\Annotation\Exceptions\RuntimeException] exception 'Wingu\OctopusCore\Reflection\Annotation\Exceptions\RuntimeException' with message 'The name of the parameter does not start with "$".'

And class looks like this:

```
namespace app\models\SOAP;

/**
 * This is the model, that will be used to build the WSDL
 * @author Philipp Frenzel <philipp@frenzel.net>
 */

class SearchRequest
{
  /**
   * @var string apikey pls check your account for details
   * @soap
   */
  public $apikey;
  
  /**
   * @var string key the external key, that will be used as return identification to the requester
   * @soap
   */
  public $key;

  /**
   * @var string query the party name, that will be used to lookup by the search allgorithems
   * @soap
   */
  public $query;

  /**
   * @var string country ISO-2 Country Code (2 digits)
   * @soap
   */
  public $country;

  /**
   * @var integer pageSize number of records, that will be returned by the request
   * @soap
   */
  public $pageSize;

  /**
   * @var string listIds list of ids, that will be searched
   * @soap
   */
  public $listIds;

}
```

**Comment by dragosprotung** [comment]
This exception is thrown when parsing ```@param``` tags. They are usually associated with annotations on methods / functions. Your example class has no methods.

I assume you omitted the rest of your class.

Make sure the annotation for a parameter of a function / method is in the form ```@param string $parameterName Parameter description.```
